In [1]:
import tensorflow as tf
#physical_devices = tf.config.list_physical_devices('CPU')
physical_devices = tf.config.list_physical_devices('GPU')

In [2]:
#tf.config.experimental.set_memory_growth(physical_devices[0], enable=True)
physical_devices

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
#test
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.8123, 0.9864, 0.4598],
        [0.9068, 0.1735, 0.5945],
        [0.6450, 0.6027, 0.6310],
        [0.8930, 0.6163, 0.6383],
        [0.3693, 0.4441, 0.9488]])


In [4]:
#test
torch.cuda.is_available()

True

In [5]:
#! pip install transformers
#! conda install pytorch torchvision torchaudio cudatoolkit=10.1 -c pytorch
#! pip3 install torch==1.7.0 torchvision==0.8.1 -f https://download.pytorch.org/whl/cu101/torch_stable.html
#! pip install tensorflow
! nvidia-smi

Wed Nov 23 14:51:50 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-PCI...  Off  | 00000000:61:00.0 Off |                    0 |
| N/A   32C    P0    33W / 250W |      3MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# Logits Extractor
>
> Extracting Tensor Logits from a given Neural Code Model @danaderp
>

In [ ]:
def params(): 
    return {
                'big_table_path' : '/workspaces/CausalCodeCapability/data/' 
}

In [6]:
pwd

'/workspaces/CausalCodeCapability/experimental_notebooks'

# Data Upload

In [22]:
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers import pipeline

In [14]:
#pip list
#! pip install git+https://github.com/huggingface/transfomers.git


In [23]:
#tokenizer = AutoTokenizer.from_pretrained("Salesforce/codegen-2B-mono")
#tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-j-6B")
#generator = pipeline('text-generation', model='EleutherAI/gpt-neo-1.3B')
#model = AutoModelForCausalLM.from_pretrained("EleutherAI/gpt-j-6B")
generator = pipeline('text-generation', model='EleutherAI/gpt-neo-125M')


Downloading:   0%|          | 0.00/0.98k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/502M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/560 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/878k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/357 [00:00<?, ?B/s]

In [32]:
generator2 = pipeline('text-generation', model='EleutherAI/gpt-neo-1.3B')


In [31]:
generator("EleutherAI has", do_sample=True, min_length=20)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'EleutherAI has reported that the EY-like Ewingle and B2-like E'}]

In [30]:
generator("for(int i= ", do_sample=True, min_length=1000)


Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'for(int i=  0;  i<=i+1; i++) { '}]

In [33]:
generator2("for(int i= ", do_sample=True, min_length=1000)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'for(int i=   0; i< 3; i++) { // start of iteration 4:\n                System.out.println(i+1);\n '}]

In [34]:

generator2.tokenizer.get_vocab_size()

AttributeError: 'GPT2TokenizerFast' object has no attribute 'get_vocab_size'

In [35]:
type(generator2)

transformers.pipelines.text_generation.TextGenerationPipeline

In [36]:
from transformers import GPTNeoForCausalLM, GPT2Tokenizer
model = GPTNeoForCausalLM.from_pretrained("EleutherAI/gpt-neo-1.3B")
tokenizer = GPT2Tokenizer.from_pretrained("EleutherAI/gpt-neo-1.3B")

In [53]:
type(model)

transformers.models.gpt_neo.modeling_gpt_neo.GPTNeoForCausalLM

In [ ]:
model.

In [72]:
tokenizer.get_vocab()

{'!': 0,
 '"': 1,
 '#': 2,
 '$': 3,
 '%': 4,
 '&': 5,
 "'": 6,
 '(': 7,
 ')': 8,
 '*': 9,
 '+': 10,
 ',': 11,
 '-': 12,
 '.': 13,
 '/': 14,
 '0': 15,
 '1': 16,
 '2': 17,
 '3': 18,
 '4': 19,
 '5': 20,
 '6': 21,
 '7': 22,
 '8': 23,
 '9': 24,
 ':': 25,
 ';': 26,
 '<': 27,
 '=': 28,
 '>': 29,
 '?': 30,
 '@': 31,
 'A': 32,
 'B': 33,
 'C': 34,
 'D': 35,
 'E': 36,
 'F': 37,
 'G': 38,
 'H': 39,
 'I': 40,
 'J': 41,
 'K': 42,
 'L': 43,
 'M': 44,
 'N': 45,
 'O': 46,
 'P': 47,
 'Q': 48,
 'R': 49,
 'S': 50,
 'T': 51,
 'U': 52,
 'V': 53,
 'W': 54,
 'X': 55,
 'Y': 56,
 'Z': 57,
 '[': 58,
 '\\': 59,
 ']': 60,
 '^': 61,
 '_': 62,
 '`': 63,
 'a': 64,
 'b': 65,
 'c': 66,
 'd': 67,
 'e': 68,
 'f': 69,
 'g': 70,
 'h': 71,
 'i': 72,
 'j': 73,
 'k': 74,
 'l': 75,
 'm': 76,
 'n': 77,
 'o': 78,
 'p': 79,
 'q': 80,
 'r': 81,
 's': 82,
 't': 83,
 'u': 84,
 'v': 85,
 'w': 86,
 'x': 87,
 'y': 88,
 'z': 89,
 '{': 90,
 '|': 91,
 '}': 92,
 '~': 93,
 '¡': 94,
 '¢': 95,
 '£': 96,
 '¤': 97,
 '¥': 98,
 '¦': 99,
 '§': 100

In [73]:
len(tokenizer.get_vocab())

50257

In [42]:
prompt = "def get_mean_probs(df: pd.DataFrame, model: Model, n: Optional[int] = None): \
    """ \
    "Get the mean probability of each token that the model" \
    "should predict for an entire pandas dataframe."\
    "if n is None:" \
        "n = len(df)" \
    "# setup container lists for the number of occurrences and sum of probabilities for each token" \
    "counts = [0] * model.tokenizer.get_vocab_size()" \
    "sum_probs = [0.0] * model.tokenizer.get_vocab_size()"

In [43]:
input_ids = tokenizer(prompt, return_tensors="pt").input_ids

In [76]:
type(model)

transformers.models.gpt_neo.modeling_gpt_neo.GPTNeoForCausalLM

In [59]:
input_ids.shape

torch.Size([1, 123])

In [78]:
#Output is the class CausalLMOutputWithPast (https://huggingface.co/transformers/v4.10.1/main_classes/output.html?highlight=causallmoutputwithpast)
#logits (torch.FloatTensor of shape (batch_size, sequence_length, config.vocab_size)) – Prediction scores of the language modeling head (scores for each vocabulary token before SoftMax).
output = model(input_ids=input_ids)

In [79]:
output.logits.shape

torch.Size([1, 123, 50257])

In [74]:
output.logits

tensor([[[ -4.7163,  -4.1678,  -8.0573,  ..., -14.3003, -12.5503, -10.1957],
         [ -9.1358,  -7.5095,  -9.0157,  ..., -19.7905, -16.6783, -11.4492],
         [-10.6732,  -8.5573,  -7.7642,  ..., -15.8004, -16.4903, -12.3207],
         ...,
         [-16.9420, -15.7932, -14.1912,  ..., -23.7035, -22.8659, -20.2982],
         [-15.1844, -11.9999,  -7.8559,  ..., -24.4472, -20.0692, -12.8104],
         [-11.7155,  -9.0382,  -1.4850,  ..., -20.0199, -16.5161,  -8.2457]]],
       grad_fn=<UnsafeViewBackward0>)

In [86]:
#Based on the response here: https://stackoverflow.com/questions/62852940/how-to-get-immediate-next-word-probability-using-gpt2-model
next_token_logits = output[0][:, -1, :]


In [87]:
next_token_logits

tensor([[-11.7155,  -9.0382,  -1.4850,  ..., -20.0199, -16.5161,  -8.2457]],
       grad_fn=<SliceBackward0>)

In [88]:
next_token_logits.shape

torch.Size([1, 50257])

In [95]:
sum(next_token_logits[0])

tensor(-881254.1875, grad_fn=<AddBackward0>)

In [89]:
soft = torch.nn.Softmax(dim=1)
next_token_distribution = soft(next_token_logits)

In [90]:
next_token_distribution.shape

torch.Size([1, 50257])

In [94]:
sum(next_token_distribution[0])

tensor(0.9999, grad_fn=<AddBackward0>)

In [48]:
gen_tokens = model.generate(input_ids, do_sample=True, temperature=0.9, max_length=200,)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [55]:
gen_tokens

tensor([[ 4299,   651,    62, 32604,    62,  1676,  1443,     7,  7568,    25,
           279,    67,    13,  6601, 19778,    11,  2746,    25,  9104,    11,
           299,    25, 32233,    58,   600,    60,   796,  6045,  2599,   220,
           220,   220,   220,  3497,   262,  1612, 12867,   286,  1123, 11241,
           326,   262,  4981,    71,   426,  4331,   329,   281,  2104, 19798,
           292,  1366, 14535,    13,   361,   299,   318,  6045,    25,    77,
           796, 18896,     7,  7568,     8,     2,  9058,  9290,  8341,   329,
           262,  1271,   286, 40279,   290,  2160,   286, 39522,   329,  1123,
         11241,  9127,    82,   796,   685,    15,    60,  1635,  2746,    13,
         30001,  7509,    13,  1136,    62, 18893,   397,    62,  7857,  3419,
         16345,    62,  1676,  1443,   796,   685,    15,    13,    15,    60,
          1635,  2746,    13, 30001,  7509,    13,  1136,    62, 18893,   397,
            62,  7857,  3419,  7783,   954,    82,  

In [49]:
gen_text = tokenizer.batch_decode(gen_tokens)[0]

In [50]:
gen_text

'def get_mean_probs(df: pd.DataFrame, model: Model, n: Optional[int] = None):     Get the mean probability of each token that the modelshould predict for an entire pandas dataframe.if n is None:n = len(df)# setup container lists for the number of occurrences and sum of probabilities for each tokencounts = [0] * model.tokenizer.get_vocab_size()sum_probs = [0.0] * model.tokenizer.get_vocab_size()return counts + sum_probs# count the number of model predictions if needed\n\ndef get_model_probs(df: pd.DataFrame, model: Model): get_model_probs_counts, get_mean_probs = get_means, get_means_probs(model)\n\n# build the mean'